name: CI CD

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: CI-CD
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clean up
      run: Remove-Item -Path scripts.zip -Force -ErrorAction Ignore

    - name: Zip
      run: Compress-Archive -Path scripts -DestinationPath scripts.zip

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: game-assets
        path: scripts.zip

    - name: Release
      uses: xresloader/upload-to-github-release@v1.6.0
      with:
        file: scripts.zip
        token: ${{ secrets.TOKEN }}
        default_release_name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        draft: false
