name: CI CD

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: CI-CD
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clean up
      run: |
        Remove-Item -Path Debug.zip -Force -ErrorAction Ignore
        Remove-Item -Path Release.zip -Force -ErrorAction Ignore

    - name: Build zips
      run: python build.py

    - name: Release Release.zip
      uses: xresloader/upload-to-github-release@v1.6.0
      with:
        file: Release.zip
        token: ${{ secrets.TOKEN }}
        default_release_name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        draft: false

    - name: Release Debug.zip
      uses: xresloader/upload-to-github-release@v1.6.0
      with:
        file: Debug.zip
        token: ${{ secrets.TOKEN }}
        default_release_name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        draft: false
